[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx prisma migrate deploy"

[deploy]
startCommand = "node src/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production" 